services:
  # nginx:
  #   image: nginx:latest
  #   container_name: prod_nginx
  #   volumes:
  #     - ./vol/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./vol/app:/var/www/html
  #   networks:
  #     production_net:
  #       ipv4_address: 172.30.0.10
  #   dns: 172.20.0.10

  # php:
  #   build:
  #     dockerfile: ./php.Dockerfile
  #   container_name: prod_php
  #   volumes:
  #     - ./vol/app:/var/www/html
  #   networks:
  #     production_net:
  #       ipv4_address: 172.30.0.12
  #   dns: 172.20.0.10

  # postgres_prod:
  #   image: postgres:14
  #   container_name: prod_postgres
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - ./vol/postgres_data:/var/lib/postgresql/data
  #   networks:
  #     production_net:
  #       ipv4_address: 172.30.0.11
  #   dns: 172.20.0.10

#################################################################

  # apache:
  #   build:
  #       dockerfile: ./apache.Dockerfile
  #   container_name: dev_webapi
  #   volumes:
  #     - ./vol/html:/var/www/html
  #   networks:
  #     development_net:
  #       ipv4_address: 172.40.0.10
  #   dns: 172.20.0.10

  # mysql:
  #   image: mysql:5.7
  #   container_name: dev_mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - ./vol/mysql_data:/var/lib/mysql
  #   networks:
  #     development_net:
  #       ipv4_address: 172.40.0.11
  #   dns: 172.20.0.10

  # ssh_dev:
  #   build:
  #       dockerfile: ./ssh_dev.Dockerfile
  #   container_name: dev_ssh
  #   volumes:
  #     - ./vol/ssh_dev/sshd_config:/etc/ssh/sshd_config
  #     - ./vol/ssh_dev/home:/home
  #     - ./vol/ssh_dev/sshd-pam:/etc/pam.d/sshd
  #   networks:
  #     development_net:
  #       ipv4_address: 172.40.0.20
  #   dns: 172.20.0.10

  # ftp:
  #     build:
  #       dockerfile: ftp.Dockerfile
  #     container_name: ftp_publico
  #     volumes:
  #       - ./vol/samba/publico:/home/publico:ro
  #     networks:
  #       development_net:
  #         ipv4_address: 172.40.0.40
  #     dns: 172.20.0.10

  samba:
    image: dperson/samba
    container_name: samba_services
    volumes:  
      - ./vol/samba/desarrollo:/mnt/desarrollo
      - ./vol/samba/revision:/mnt/revision
      - ./vol/samba/publico:/mnt/publico
      - ./vol/samba/init_samba.sh:/init_samba.sh
    networks:
      development_net:
        ipv4_address: 172.40.0.30
    dns: 172.20.0.10
    command: bash /init_samba.sh

  apache:
    image: httpd:latest
    container_name: apache_server
    ports:
      - "8082:80"
    volumes:
      - ./vol/samba/publico:/usr/local/apache2/mmt/ftp/publico:ro
      - ./vol/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./vol/apache/index.html:/usr/local/apache2/htdocs/index.html
    networks:
      development_net:
        ipv4_address: 172.40.0.50
    dns: 172.20.0.10
    command: >
          bash -c "
          mkdir -p /usr/local/apache2/conf/auth && \
          htpasswd -cb /usr/local/apache2/conf/auth/.htpasswd documentos GraTiS! && \
          httpd-foreground && \
          chmod -R o+r /usr/local/apache2/mmt/ftp/publico
          "

#################################################################

  # dns:
  #   image: ubuntu/bind9:latest 
  #   container_name: dns_services
  #   networks:
  #     services_net:
  #       ipv4_address: 172.20.0.10
  #   volumes:
  #     - ./vol/bind:/etc/bind
  #     - ./vol/run/named:/var/run/named

  # nas:
  #   build:
  #     dockerfile: ./nas.Dockerfile
  #   container_name: nas_services
  #   networks:
  #     services_net:
  #       ipv4_address: 172.20.0.12
  #   volumes:
  #     - ./vol/backups:/backups
  #   dns: 172.20.0.10

  # ssh_ser:
  #   build:
  #       dockerfile: ./ssh_ser.Dockerfile
  #   container_name: ssh_services
  #   volumes:
  #     - ./vol/ssh_ser/sshd_config:/etc/ssh/sshd_config
  #     - ./vol/ssh_ser/home:/home
  #   networks:
  #     services_net:
  #       ipv4_address: 172.20.0.20
  #   dns: 172.20.0.10

#################################################################

networks:
  production_net:
    driver: macvlan
    driver_opts:
      parent: "ens20"
    ipam:
      config:
       -  subnet: 172.30.0.0/24
          gateway: 172.30.0.1
  services_net:
    driver: macvlan
    driver_opts:
      parent: "ens19"
    ipam:
      config:
       -  subnet: 172.20.0.0/24
          gateway: 172.20.0.1
  development_net:
    driver: macvlan
    driver_opts:
      parent: "ens21"
    ipam:
      config:
       -  subnet: 172.40.0.0/24