services:
  nginx:
    image: nginx:latest
    volumes:
      - ./vol/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./vol/app:/var/www/html
    ports:
      - "8080:80"
    networks:
      production_net:
        ipv4_address: 172.30.0.10

  php:
    build:
      dockerfile: ./php.Dockerfile
    volumes:
      - ./vol/app:/var/www/html
    networks:
      production_net:
        ipv4_address: 172.30.0.12

  postgres_prod:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      production_net:
        ipv4_address: 172.30.0.11
      services_net:
        ipv4_address: 172.20.0.11

networks:
  production_net:
    driver: macvlan
    driver_opts:
      parent: "ens20"
    ipam:
      config:
       -  subnet: 172.30.0.0/24
          gateway: 172.30.0.1
  services_net:
    driver: macvlan
    driver_opts:
      parent: "ens19"
    ipam:
      config:
       -  subnet: 172.20.0.0/24
          gateway: 172.20.0.1
volumes:
  postgres_data:
