version: '3'

services:
  dns:
    image: ubuntu/bind9:latest 
    container_name: dns_nas_services
    user: bind:bind  # Ejecutar como usuario bind
    networks:
      services_net:
        ipv4_address: 172.20.0.10
    volumes:
      - ./vol/bind:/etc/bind
      - ./vol/cache:/var/cache/bind
      - ./vol/run/named:/var/run/named 
    ports:
      - '53:53/udp'
      - '53:53/tcp'
    environment:
      - TZ=UTC  # Opcional: establecer zona horaria
    healthcheck:
      test: ["CMD", "named-checkconf", "/etc/bind/named.conf"]
      interval: 30s
      timeout: 5s
      retries: 3
  # nas:
  #   image: ubuntu:latest
  #   container_name: nas_services
  #   networks:
  #     - services_net
  #   volumes:
  #     - ./backups:/backups
  #   entrypoint: ["/bin/sh", "-c", "apt update && apt install -y rsync cron && cron -f"]
  #   #command: bash -c "echo '0 1 * * * /backups/backup.sh' | crontab - && cron -f"

networks:
  services_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
