version: '3'
services:
  webapi_prod:
    image: mywebapiprod
    container_name: prod_webapi
    networks:
      production_net:
        ipv4_address: 172.30.0.10
    ports:
      - "80:80"
    depends_on:
      - postgres_prod

  postgres_prod:
    image: postgres:14
    container_name: prod_postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      production_net:
        ipv4_address: 172.30.0.11
      services_net:
        ipv4_address: 172.20.0.11

networks:
  production_net:
    external: true
  services_net:
    external: true
