version: '3.1'

services:

  apache:
      image: httpd:latest
      container_name: dev_apache
      ports:
        - "8081:80"
      volumes:
        - ./apache.conf:/usr/local/apache2/conf/httpd.conf:ro
        - ./app:/var/www/html
      restart: always
      networks:
        - development_net

  php:
    image: php:8.2-fpm
    container_name: dev_php
    volumes:
      - ./app:/var/www/html
    command: >
      sh -c "apt-get update && apt-get install -y libpq-dev &&
             docker-php-ext-install pdo pdo_mysql &&
             docker-php-entrypoint php-fpm"
    networks:
      - development_net

  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    restart: always
    networks:
      - development_net

networks:
  development_net:
    ipam:
      config:
        - subnet: 172.40.0.0/24