version: '3.1'

services:

  apache:
    image: php:7.4-apache
    container_name: dev_webapi
    volumes:
      - ./html:/var/www/html
    ports:
      - "8081:80"
    restart: always
    networks:
      development_net:
        ipv4_address: 172.40.0.10
    command: >
      sh -c "apt-get update && apt-get install -y libpq-dev && 
      docker-php-ext-install pdo pdo_mysql && 
      docker-php-entrypoint apache2-foreground"


  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    restart: always
    networks:
      development_net:
        ipv4_address: 172.40.0.11

networks:
  development_net:
    ipam:
      config:
        - subnet: 172.40.0.0/24