version: '3.1'

services:

  apache:
    image: php:7.4-apache
    container_name: dev_webapi
    volumes:
      - ./html:/var/www/html
    ports:
      - "8081:80"
    networks:
      development_net:
        ipv4_address: 172.40.0.10
    command: >
      sh -c "apt-get update && apt-get install -y libpq-dev && 
      docker-php-ext-install pdo pdo_mysql && 
      docker-php-entrypoint apache2-foreground"


  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    networks:
      development_net:
        ipv4_address: 172.40.0.11
    volumes:
      - ./mysql_data:/var/lib/mysql

  nas:
    image: ubuntu:latest
    container_name: nas_services
    networks:
      - services_net
      - development_net
    volumes:
      - ./backups:/backups
    entrypoint: ["/bin/sh", "-c", "apt update && apt install -y rsync mysql-client postgresql-client cron && cron -f"]
    #command: bash -c "echo '0 1 * * * /backups/backup.sh' | crontab - && cron -f"

networks:
  development_net:
    ipam:
      config:
        - subnet: 172.40.0.0/24
  services_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24